version: '3.9'

services:

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: albert-health
      MINIO_SECRET_KEY: nF95KPEfxZFQAFT0RLFzsf8/diIyZBwQz0RkictMn70=
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address :9001 /data

  app:
    build:
      context: ./project
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - minio
