version: '3.9'

services:

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address :9001 /data

  app:
    build:
      context: ./project
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - minio
