version: '3.9'

networks:
  my_network:


services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: albert-health
      MINIO_SECRET_KEY: nF95KPEfxZFQAFT0RLFzsf8/diIyZBwQz0RkictMn70=
    volumes:
      - ./data:/data
    ports:
      - "9000:9001"
    networks:
      - my_network
    command: server --console-address :9001 /data

  app:
    build:
      context: ./project
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    environment:
      PUBLIC_ADRESS: localhost
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: albert-health
      MINIO_SECRET_KEY: nF95KPEfxZFQAFT0RLFzsf8/diIyZBwQz0RkictMn70=
      MINIO_BUCKET_NAME: albert-bucket
    depends_on:
      - minio
    networks:
      - my_network
