name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: 20

    - name: Build with Maven
      run: mvn -B package --file project/pom.xml

    - name: Test with Maven
      run: mvn test --file project/pom.xml
